### ISSUE TITLE
Fails with collapsed regions

### ISSUE THREAD

**Issue by ite-jankl** [bhaeussermann/ScrollWithStationaryCursor#2]
When scrolling through collapsed regions, it opens them.

However, when having collapse regions/blocks and you start at a high enough line, scrolling will not have any effect even when there is still area to scroll.

In the 5006 line file I am seeing this right now it does not work from line 993 on even. So most of the file is not scrollable (down).

**Comment by bhaeussermann** [comment]
@ite-klass Ok, this was quite a tricky one, as it seems the VisualStudio Interop API does not provide access to the region-info. 

I pushed my changes to [this branch](https://github.com/bhaeussermann/ScrollWithStationaryCursor/tree/bhaeussermann-collapsed-regions) so you can pull it and test. See the [pull request](https://github.com/bhaeussermann/ScrollWithStationaryCursor/pull/3) for a brief description of the change.

Kindly let me know if the code works for you, and if so I will merge the change to master and publish a new version of the extension on the Visual Studio Marketplace.

By the way, were you able to set up the Visual Studio SDK as per the last comment on the [previous issue](https://github.com/bhaeussermann/ScrollWithStationaryCursor/issues/1)?

**Comment by ite-jankl** [comment]
Thank you for your effort

No, I do not have a build environment prepared. So I can also not test a source branch.

But the issue should be reproducible quite easily? With a big file with regions?

**Comment by ite-jankl** [comment]
Crazy solution/workaround :)

Did you communicate with upstream if there is anything more feasible? You said the API does not provide region-info data. Is there an upstream ticket for it?

**Comment by bhaeussermann** [comment]
I just [asked](https://social.msdn.microsoft.com/Forums/en-US/6b06ef1c-94a8-4871-86e4-085827c899ea/visualstudio-extension-api-acquire-region-info?forum=visualstudiogeneral) on the MSDN-forum. Will wait and see what they say.

**Comment by bhaeussermann** [comment]
@ite-klass As they informed on [my question](https://social.msdn.microsoft.com/Forums/en-US/6b06ef1c-94a8-4871-86e4-085827c899ea/visualstudio-extension-api-acquire-region-info?forum=visualstudiogeneral) we can acquire the region-info from the IOutliningManager. One needs to jump through a few hoops though to get hold of an IOutliningManager object.

I pushed my changes to [this branch](https://github.com/bhaeussermann/ScrollWithStationaryCursor/tree/bhaeussermann-collapsed-regions-region-info) and created a new [pull request](https://github.com/bhaeussermann/ScrollWithStationaryCursor/pull/4).
Unfortunately, it turns out there are quite a number of cases to cater for, and the code turned out to be much longer than the first solution. However, I think this code makes more sense, as it is not so much of a work-around as the other change, and I have a feeling it will have fewer bugs.

Do let me know if you approve of this change.

**Comment by ite-jankl** [comment]
Awesome, thank you very much for your effort

I have not reviewed the code, but using the dedicated API seems better. Unfortunate if that ends up longer or more complicated.

**Comment by bhaeussermann** [comment]
@ite-klass I just published the new version 1.2 on the Visual Studio Marketplace which supports skipping over collapsed regions.

**Comment by ite-jankl** [comment]
@bhaeussermann Thank you very much! Seems to work fine now!

How come you don’t release version tags in Git/push them to GitHub?

**Comment by bhaeussermann** [comment]
@ite-klass That sounds like a good suggestion. I will try to incorporate that convention in future.
